read = b'\x52'
write = b'\x57'

reg_prod_id = b'\x2C00'
reg_sens_sts = b'\x2C01'
reg_meas_rate_h = b'\x2C02'
reg_meas_rate_l = b'\x2C03'
reg_meas_conf = b'\x2C04'
reg_co2ppm_h = b'\x2C05'
reg_co2ppm_l = b'\x2C06'
reg_meas_sts = b'\x2C07'
reg_int_cfg = b'\x2C08'
reg_alarm_th_h = b'\x2C09'
reg_alarm_th_l = b'\x2C0A'
reg_pres_ref_h = b'\x2C0B'
reg_pres_ref_l = b'\x2C0C'
reg_calib_ref_h = b'\x2C0D'
reg_calib_ref_l = b'\x2C0E'
reg_scratch_pad = b'\x2C0F'
reg_soft_reset = b'\x2c10'
ACK = b'\x06'
NACK =  b'\x15'
### Reset Values ###
soft_rest = b'\x2CA3'
end_message = b'\x0A'

### Measurement Configuration ###
idle_mode = b'\x2C00'
single_shot_mode = b'\x2C01'
continuous_mode = b'\x2C02'
